### ISSUE TITLE
麻烦看看洪恩双语绘本，谢谢

### ISSUE THREAD

**Issue by fangpidedongsun** [yukerui/httpCatcher-rules#1]

**Comment by yukerui** [comment]
和我说一下这个app里有哪些功能是需要会员的

**Comment by fangpidedongsun** [comment]
> 和我说一下这个app里有哪些功能是需要会员的

凡是没有标注Free的绘本只能查看几页，想要阅读完整的绘本就需要会员了，当免费的页数看完后，就会弹出购买会员的选项。标记为Free的不需要会员也可以查看全部内容。

**Comment by yukerui** [comment]
ok，我试下啊，不一定能行

**Comment by fangpidedongsun** [comment]
> ok，我试下啊，不一定能行

不行也没关系，先谢谢大神了

**Comment by yukerui** [comment]
我看了一下，这个是服务端做校验的，估计是改不了，要是能改的话我会更新，到时候给你回，很抱歉

**Comment by fangpidedongsun** [comment]
> 我看了一下，这个是服务端做校验的，估计是改不了，要是能改的话我会更新，到时候给你回，很抱歉

太感谢了

**Comment by yukerui** [comment]
兄弟，我写完了，[教程](https://blog.930113.xyz/2020/05/14/%E7%BB%88%E6%9E%81%E8%9B%87%E7%9A%AE%E4%B9%8Bcharles%E4%BF%AE%E6%94%B9%E6%B4%AA%E6%81%A9%E5%8F%8C%E8%AF%AD%E7%BB%98%E6%9C%AC%EF%BC%8C%E6%9C%89%E5%B0%8F%E6%9C%8B%E5%8F%8B%E7%9A%84%E8%BF%9B%E6%9D%A5%E7%9C%8B%E7%9C%8B%EF%BC%8C%E8%B6%85%E8%AF%A6%E7%BB%86%E7%9A%84%E5%93%A6/), 文件在master里，加个star吧

**Comment by fangpidedongsun** [comment]
> 兄弟，我写完了，[教程](https://blog.930113.xyz/2020/05/14/%E7%BB%88%E6%9E%81%E8%9B%87%E7%9A%AE%E4%B9%8Bcharles%E4%BF%AE%E6%94%B9%E6%B4%AA%E6%81%A9%E5%8F%8C%E8%AF%AD%E7%BB%98%E6%9C%AC%EF%BC%8C%E6%9C%89%E5%B0%8F%E6%9C%8B%E5%8F%8B%E7%9A%84%E8%BF%9B%E6%9D%A5%E7%9C%8B%E7%9C%8B%EF%BC%8C%E8%B6%85%E8%AF%A6%E7%BB%86%E7%9A%84%E5%93%A6/), 文件在master里，加个star吧

太太太太感谢了，早就star了，博客也收藏啦，期待大神继续输出好东西

**Comment by fangpidedongsun** [comment]
> 兄弟，我写完了，[教程](https://blog.930113.xyz/2020/05/14/%E7%BB%88%E6%9E%81%E8%9B%87%E7%9A%AE%E4%B9%8Bcharles%E4%BF%AE%E6%94%B9%E6%B4%AA%E6%81%A9%E5%8F%8C%E8%AF%AD%E7%BB%98%E6%9C%AC%EF%BC%8C%E6%9C%89%E5%B0%8F%E6%9C%8B%E5%8F%8B%E7%9A%84%E8%BF%9B%E6%9D%A5%E7%9C%8B%E7%9C%8B%EF%BC%8C%E8%B6%85%E8%AF%A6%E7%BB%86%E7%9A%84%E5%93%A6/), 文件在master里，加个star吧

大神 我试了一下 绘本确实都显示free了 但是下载后还是一样 只能试读几页
