### ISSUE TITLE
能帮忙搞定豆瓣阅读吗？谢谢大神

### ISSUE THREAD

**Issue by upupup3286** [yukerui/httpCatcher-rules#2]
看了博客想学习一下网球规则的修改，但是自己没有计算机基础觉得好难。。。

**Comment by yukerui** [comment]
需要豆瓣阅读的什么啊

**Comment by yukerui** [comment]
它自动送了我个7天的会员，我先发出来，你测试下，有问题在这里报

**Comment by upupup3286** [comment]
> 需要豆瓣阅读的什么啊

我想看豆瓣阅读里的原创小说，需要会员，httpcatcher可以修改规则吗？我看了一下你修改会员的方法，找user，vip试了半天还是摸不着头脑，哈哈

**Comment by yukerui** [comment]
我更新了，你试试，不能用的话再回一个

**Comment by yukerui** [comment]
右上角的star点一波，救救孩子吧，啥都没人看

**Comment by ldcr1319** [comment]
> 右上角的star点一波，救救孩子吧，啥都没人看

可以帮忙看下宝宝巴士奇妙屋能不能搞定吗

**Comment by yukerui** [comment]
> > 右上角的star点一波，救救孩子吧，啥都没人看
> 
> 可以帮忙看下宝宝巴士奇妙屋能不能搞定吗

新开一个issues吧，这个解决了我要关掉了，开issue麻烦按照模版来写
