### ISSUE TITLE
HttpCatcher教程

### ISSUE THREAD

**Issue by LinLoveRunning** [yukerui/httpCatcher-rules#3]
大佬，可以多出一些关于httpcatcher的教程吗？😜

**Comment by yukerui** [comment]
当然可以啊，你觉得需要哪些软件的呀，我看看好不好改

**Comment by LinLoveRunning** [comment]
> 当然可以啊，你觉得需要哪些软件的呀，我看看好不好改
想要Lingvist，一款语言学习的app。鼓捣了大半天，用抓包app找到了试用时长值，订阅到期值，仍然搞不定😂

**Comment by yukerui** [comment]
收到啦，和我说下哪些是需要会员功能的

**Comment by LinLoveRunning** [comment]
yukerui:
      您好！这个应用是这样的：先给你试用6天，到期后用户只能学习基础的单词，无法再更深一步的学习下去，而且在每日挑战中只能挑战一个，而会员可以无限制挑战。
另外，我刚刚在你的博客看了下教程（用网球破解轻听英语下载限额），照着教程做发现并没有破解，后来我把正则表达式下面查找栏里的+删了就可以了，但我不清楚为什么—没怎么学过编程类知识。打搅你了！

祝好！




| |
蓝加洪
|
|
邮箱：john_hjlan@163.com
|

签名由 网易邮箱大师 定制

在2020年05月14日 16:33，lovexl 写道：

收到啦，和我说下哪些是需要会员功能的

**Comment by yukerui** [comment]
> yukerui: 您好！这个应用是这样的：先给你试用6天，到期后用户只能学习基础的单词，无法再更深一步的学习下去，而且在每日挑战中只能挑战一个，而会员可以无限制挑战。 另外，我刚刚在你的博客看了下教程（用网球破解轻听英语下载限额），照着教程做发现并没有破解，后来我把正则表达式下面查找栏里的+删了就可以了，但我不清楚为什么—没怎么学过编程类知识。打搅你了！ 祝好！ | | 蓝加洪 | | 邮箱：john_hjlan@163.com | 签名由 网易邮箱大师 定制 在2020年05月14日 16:33，lovexl 写道： 收到啦，和我说下哪些是需要会员功能的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已经搞定了是吗，太棒了，+在正则表达式中表示匹配多个，比如000111这种需要\d+，而只有一个的话就不用了，比如0就用\d

**Comment by LinLoveRunning** [comment]
你可能误解我了，我上一封的邮件指的是我在跟着你的教程去重新破解轻听英语时碰到的问题，而非破解lingvist。现在我照着教程已经成功把轻听英语里的VIP年限更改成功了🤔。但lingvist我还是搞不定，我尝试只把订阅时间改成更远的日期，但app里还是显示试用6天😭。




| |
蓝加洪
|
|
邮箱：john_hjlan@163.com
|

签名由 网易邮箱大师 定制

在2020年05月14日 17:24，lovexl 写道：

yukerui: 您好！这个应用是这样的：先给你试用6天，到期后用户只能学习基础的单词，无法再更深一步的学习下去，而且在每日挑战中只能挑战一个，而会员可以无限制挑战。 另外，我刚刚在你的博客看了下教程（用网球破解轻听英语下载限额），照着教程做发现并没有破解，后来我把正则表达式下面查找栏里的+删了就可以了，但我不清楚为什么—没怎么学过编程类知识。打搅你了！ 祝好！ | | 蓝加洪 | | 邮箱：john_hjlan@163.com | 签名由 网易邮箱大师 定制 在2020年05月14日 16:33，lovexl 写道： 收到啦，和我说下哪些是需要会员功能的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已经搞定了是吗，太棒了，+在正则表达式中表示匹配多个，比如000111这种需要\d+，而只有一个的话就不用了，比如0就用\d

**Comment by yukerui** [comment]
ok，我知道这个了，别急啊，我一个个看看，我现在在弄博客的评论呢

**Comment by LinLoveRunning** [comment]
没事，你先忙，麻烦你了！




| |
蓝加洪
|
|
邮箱：john_hjlan@163.com
|

签名由 网易邮箱大师 定制

在2020年05月14日 17:59，lovexl 写道：

ok，我知道这个了，别急啊，我一个个看看，我现在在弄博客的评论呢

**Comment by yukerui** [comment]
我昨天看了这个，它送了我会员，现在不太好改，等会员过期了我再看看
