### ISSUE TITLE
洪恩故事

### ISSUE THREAD

**Issue by fangpidedongsun** [yukerui/httpCatcher-rules#4]
大神 我按照你解锁绘本的思路 解锁了一下洪恩故事 但是我都弄成试听了 但是付费的无法播放 查看代码好像是下载MP3的时候需要进行一个验证 
不知道是不是这样 还麻烦大佬看一下
APP下载：
https://apps.apple.com/cn/app/%E6%B4%AA%E6%81%A9%E6%95%85%E4%BA%8B-%E5%84%BF%E7%AB%A5%E5%B9%BC%E5%8D%87%E5%B0%8F%E6%97%A9%E6%95%99%E5%90%AF%E8%92%99%E6%95%99%E8%82%B2/id1170391447

**Comment by yukerui** [comment]
ok，我看下，你和我说下哪些是需要会员的

**Comment by fangpidedongsun** [comment]
> ok，我看下，你和我说下哪些是需要会员的

这个软件进去看到每个故事 在封面的右上角有皇冠的标志的是可以试听前三集的 后面的就需要会员了 右上角没有皇冠的就是免费的

**Comment by yukerui** [comment]
这个确实加密了，连mp3的链接都没有了

**Comment by yukerui** [comment]
兄弟，这个没法破解，这个是从服务器端校验的，没法改

**Comment by fangpidedongsun** [comment]
> 兄弟，这个没法破解，这个是从服务器端校验的，没法改

好的 谢谢大神

**Comment by yukerui** [comment]
兄弟，我写了教程了，在发，你到时候去博客看就行了
