### ISSUE TITLE
跪求葫芦时刻杂志解锁

### ISSUE THREAD

**Issue by userzhangqg** [yukerui/httpCatcher-rules#7]
大佬，能否帮忙解锁一下葫芦时刻？

**Comment by yukerui** [comment]
麻烦按照格式发。
1.app名称
2.哪些功能是需要会员的
我能节省点时间

**Comment by userzhangqg** [comment]
APP：葫芦时刻
功能：会员杂志阅读

**Comment by yukerui** [comment]
ok,稍等啊，我回来看看，要是可以做的话会在博客更新的

**Comment by yukerui** [comment]
兄弟，这个改不了，只能改本地显示，测试没vip功能，那些vip杂志是从服务器校验的，改不了
