### ISSUE TITLE
大佬，麻烦看下未来之光APP

### ISSUE THREAD

**Issue by MNMBDD** [yukerui/httpCatcher-rules#9]
1.app名称:未来之光

2.描述：

打开APP-“全部”，里面的所有游戏都是要VIP才能解锁的，永久会员是298，屌丝买不起。

“全部”拉到下面，还有个高级训练-速度能力，就算是VIP也是要单独购买的。

拜托大佬了。

**Comment by yukerui** [comment]
兄弟加个qq群，你自己尝试下，不懂的截图我帮你看看，我最近没什么时间一个个的试了，你要是不急用的话也可以等等
